version: '3.3'

services:
   db:
     image: mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Inpecman1
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: Inpecman1

   wordpress:
     depends_on:
       - db
     build: docker/mywordpress
     volumes:
       - ./html:/var/www/html
#       - ./settings/:/usr/local/etc/php/conf.d/
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: Inpecman1
     command: "chown -R www-data:www-data /var/www/wordpress"
   phpmyadmin:
     depends_on:
       - db
     image: corbinu/docker-phpmyadmin
     links:
       - db:mysql
     ports:
       - 8181:80
     environment:
       MYSQL_PORT_3306_TCP_ADDR: db
       MYSQL_USERNAME: root
       MYSQL_ROOT_PASSWORD: Inpecman1
volumes:
    db_data: {}